# Generated by Django 4.2.7 on 2023-11-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_ver_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ver_code',
            field=models.CharField(default='398983565604', max_length=15, verbose_name='Проверочный код'),
        ),
    ]
