# Generated by Django 4.2.6 on 2023-10-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='count_views',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='creation_data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания'),
        ),
    ]
