# Generated by Django 4.2.7 on 2023-11-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_modified_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего изменения'),
        ),
    ]
